library(tidyverse)
library(colorspace, RColorBrewer)
library(gridExtra)
library(cluster, factoextra)
library(WeightedCluster)
library(reshape2)
library(ggplot2)

load(file="temps/ASWPBCplots")

colnames(ASWna)<-c("numberofClusters", "ASWset1na0", "ASWset1na0.4", "ASWset1na0.8", "ASWset1na1.2", "ASWset1na1.6", "ASWset1na2", "ASWset2na0", "ASWset2na0.4", "ASWset2na0.8", "ASWset2na1.2", "ASWset2na1.6", "ASWset2na2")
ASWna<-melt(ASWna, id.vars="numberofClusters")
ASWna$NAcost<-factor(rep(0:5, each=19))
plot<-ggplot(data=ASWna,aes(x=numberClusters,y=value,group=variable))
plot<-plot+geom_point( aes(group=variable, col=NAcost),size = 4)
plot<-plot+geom_line( aes(col=NAcost), size=1.5)
plot<-plot+scale_color_discrete(name="NA cost", breaks=c("0", "1", "2", "3", "4", "5"),labels=c("0", "0.4", "0.8", "1.2", "1.6", "2"))
plot<-plot+xlab("Number of Clusters")+ylab("ASW")
print(plot)

colnames(ASWna)<-c("numberofClusters", "ASWset1na0", "ASWset1na0.4", "ASWset1na0.8", "ASWset1na1.2", "ASWset1na1.6", "ASWset1na2", "ASWset2na0", "ASWset2na0.4", "ASWset2na0.8", "ASWset2na1.2", "ASWset2na1.6", "ASWset2na2")
ASWna<-melt(ASWna, id.vars="numberofClusters")
ASWna$NAcost<-factor(rep(0:5, each=19))
plot<-ggplot(data=ASWna,aes(x=numberClusters,y=value,group=variable))
plot<-plot+geom_point( aes(group=variable, col=NAcost),size = 4)
plot<-plot+geom_line( aes(col=NAcost), size=1.5)
plot<-plot+scale_color_discrete(name="NA cost", breaks=c("0", "1", "2", "3", "4", "5"),labels=c("0", "0.4", "0.8", "1.2", "1.6", "2"))
plot<-plot+xlab("Number of Clusters")+ylab("ASW")
print(plot)

colnames(PBCna)<-c("numberofClusters", "PBCset1na0", "PBCset1na0.4", "PBCset1na0.8", "PBCset1na1.2", "PBCset1na1.6", "PBCset1na2")
PBCna<-melt(PBCna, id.vars="numberofClusters")
PBCna$NAcost<-factor(rep(0:5, each=19))
plot<-ggplot(data=PBCna,aes(x=numberClusters,y=value,group=variable))
plot<-plot+geom_point( aes(group=variable, col=NAcost),size = 4)
plot<-plot+geom_line( aes( col=NAcost), size=1.5)
plot<-plot+scale_color_discrete(name="NA cost", breaks=c("0", "1", "2", "3", "4", "5"),labels=c("0", "0.4", "0.8", "1.2", "1.6", "2"))
plot<-plot+xlab("Number of Clusters")+ylab("ASW")
print(plot)

colnames(PBCnaset2)<-c("numberofClusters", "PBCset2na0", "PBCset2na0.4", "PBCset2na0.8", "PBCset2na1.2", "PBCset2na1.6", "PBCset2na2")
PBCna<-melt(PBCna, id.vars="numberofClusters")
ASWna$NAcost<-factor(rep(0:5, each=19))
plot<-ggplot(data=ASWna,aes(x=numberClusters,y=value,group=variable))
plot<-plot+geom_point( aes(group=variable, col=NAcost),size = 4)
plot<-plot+geom_line( aes( col=NAcost), size=1.5)
plot<-plot+scale_color_discrete(name="NA cost", breaks=c("0", "1", "2", "3", "4", "5"),labels=c("0", "0.4", "0.8", "1.2", "1.6", "2"))
plot<-plot+xlab("Number of Clusters")+ylab("ASW")
print(plot)