library(TraMineR)
library(tidyverse)
library(colorspace, RColorBrewer)
library(gridExtra)
library(cluster, factoextra)
library(WeightedCluster)
library(reshape2)
library(ggplot2)

load(file="temps/Clusterinfo")
load(file="temps/plotinfo")

#plotting
#ASW
colnames(ASW)<-c("numberClusters", "ASWn0", "ASWn2", "ASWb0", "ASWb2", "ASWc0", "ASWc2")
ASW<-melt(ASW, id.vars="numberClusters")
ASW$DT<-factor(rep(0:2, each=38))
ASW$NAc<-factor(rep(0:1, each=19))
plot<-ggplot(data=ASW,aes(x=numberClusters,y=value,group=variable))
plot<-plot+geom_point( aes(group=variable,color=DT),size = 4)
plot<-plot+geom_line(aes(linetype=NAc,color=DT), size=1.5)
plot<-plot + theme(axis.text.x = element_text(angle = 00, hjust = 1, size=13,color="black",face='bold'))
plot<-plot + theme(axis.text.y = element_text(angle = 00, hjust = 1, size=13,color="black",face='bold'))
plot<-plot+scale_color_discrete(name="Data Type", breaks=c("0", "1", "2"),labels=c("Nominal", "Binary", "Combined"))
plot<-plot+scale_linetype_discrete(name="NA cost", breaks=c("0", "1"),labels=c("NA cost 0", "NA cost 2"))
plot<-plot+coord_cartesian(xlim =c(1, 20),ylim=c(0.1,0.9)) 
plot<-plot + scale_y_continuous(breaks=seq(0.1,0.8,0.1))
plot<-plot+xlab("Number of Clusters")+ylab("ASW")
plot<-plot + theme(axis.title.x = element_text(face='bold', size=13))
plot<-plot + theme(axis.title.y = element_text(face='bold', size=13))
ASWplot<-plot + theme(panel.border = element_rect(colour = "black", fill=NA, size=1))
print(ASWplot)
#PBC
colnames(PBC)<-c("numberClusters", "PBCn0", "PBCn2", "PBCb0", "PBCb2", "PBCc0", "PBCc2")
PBC<-melt(PBC, id.vars="numberClusters")
PBC$DT<-factor(rep(0:2, each=38))
PBC$NAc<-factor(rep(0:1, each=19))
plot<-ggplot(data=PBC,aes(x=numberClusters,y=value,group=variable))
plot<-plot+geom_point( aes(group=variable,color=DT),size = 4)
plot<-plot+geom_line(aes(linetype=NAc,color=DT), size=1.5)
plot<-plot + theme(axis.text.x = element_text(angle = 00, hjust = 1, size=13,color="black",face='bold'))
plot<-plot + theme(axis.text.y = element_text(angle = 00, hjust = 1, size=13,color="black",face='bold'))
plot<-plot+scale_color_discrete(name="Data Type", breaks=c("0", "1", "2"),labels=c("Nominal", "Binary", "Combined"))
plot<-plot+scale_linetype_discrete(name="NA cost", breaks=c("0", "1"),labels=c("NA cost 0", "NA cost 2"))
plot<-plot+coord_cartesian(xlim =c(1, 20),ylim=c(0.1,0.9)) 
plot<-plot + scale_y_continuous(breaks=seq(0.1,0.8,0.1))
plot<-plot+xlab("Number of Clusters")+ylab("PBC")
plot<-plot + theme(axis.title.x = element_text(face='bold', size=13))
plot<-plot + theme(axis.title.y = element_text(face='bold', size=13))
PBCplot<-plot + theme(panel.border = element_rect(colour = "black", fill=NA, size=1))
print(PBCplot)

pdf("plots/PBC-ASW.pdf")
print(ASWplot)
print(PBCplot)
dev.off()