library(TraMineR)
library(tidyverse)
library(colorspace, RColorBrewer)
library(Rtsne)
library(ggplot2)
library(gridExtra)
library(grid)
library(cowplot)
library(gridGraphics)

setwd("~/Documents/my project/src/alignment-gaps-analysis")
load(file="temps/newDF5")
load(file="temps/t-snedel")
load(file="temps/setsdel")

numclust=c(2:8)
#plot
par(bg="#daedefff")
nona<-filter(reduced35, is.na(reduced35$hhsize))
table(nona$id)
seqIplots<-map2(newDF5, "hhsize", ~seqIplot(.x, sortv="from.end", main= .y))
# seqdplots<-map2(newDF5, columnNames, ~seqdplot(.x, main=.y))
# seqfplots<-map2(newDF5, columnNames, ~seqdplot(.x, main=.y))

clusters<-map(numclust, ~cutree(clusterwardset1shortdel[[3]], k=.))
clustersfac<- map(clusters, ~factor(., labels = "numclust"))
clusters2<-map(numclust, ~cutree(clusterwardset2shortdel[[3]], k=.))
clustersfac2<- map(clusters2, ~factor(., labels = "numclust"))
par(pty = "s", bg="#daedefff")
pdf("plots/seqplotsset1all.pdf")
# map(clustersfac, ~seqdplot(shortenedset1del[[3]][[1]], group = ., border = NA, main="ifchildunder8"))
map(clustersfac, ~seqIplot(shortenedset1del[[3]][[1]], sortv="from.start", group = ., border = NA, main="ifchildunder8"))
# map(clustersfac, ~seqdplot(shortenedset1del[[3]][[2]], group = ., border = NA, main="employ"))
map(clustersfac, ~seqIplot(shortenedset1del[[3]][[2]], sortv="from.start", group = ., border = NA, main="employ"))
# map(clustersfac, ~seqdplot(shortenedset1del[[3]][[3]], group = ., border = NA, main="school"))
map(clustersfac, ~seqIplot(shortenedset1del[[3]][[3]], sortv="from.start", group = ., border = NA, main="school"))
# map(clustersfac, ~seqdplot(shortenedset1del[[3]][[4]], group = ., border = NA, main="partner"))
map(clustersfac, ~seqIplot(shortenedset1del[[3]][[4]], sortv="from.start", group = ., border = NA, main="partner"))
dev.off()
pdf("plots/seqplotsset2allclusteredbyset1.pdf")
# map(clustersfac, ~seqdplot(shortenedset2del[[3]][[1]], group = ., border = NA, main="used_walkbike"))
map(clustersfac, ~seqIplot(shortenedset2del[[3]][[1]], sortv="from.start", group = ., border = NA, main="used_walkbike"))
# map(clustersfac, ~seqdplot(shortenedset2del[[3]][[2]], group = ., border = NA, main="used_public"))
map(clustersfac, ~seqIplot(shortenedset2del[[3]][[2]], sortv="from.start", group = ., border = NA, main="used_public"))
# map(clustersfac, ~seqdplot(shortenedset2del[[3]][[3]], group = ., border = NA, main="used_own"))
map(clustersfac, ~seqIplot(shortenedset2del[[3]][[3]], sortv="from.start", group = ., border = NA, main="used_own"))
dev.off()
pdf("plots/seqplotsset12clusters.pdf")
# seqdplot(shortenedset1del[[3]][[1]], group = clustersfac[[1]], border = NA, main="ifchildunder8")
seqIplot(shortenedset1del[[3]][[1]], sortv="from.start", group = clustersfac[[1]], border = NA, main="ifchildunder8")
# seqdplot(shortenedset1del[[3]][[2]], group = clustersfac[[1]], border = NA, main="employ")
seqIplot(shortenedset1del[[3]][[2]], sortv="from.start", group = clustersfac[[1]], border = NA, main="employ")
# seqdplot(shortenedset1del[[3]][[3]], group = clustersfac[[1]], border = NA, main="school")
seqIplot(shortenedset1del[[3]][[3]], sortv="from.start", group = clustersfac[[1]], border = NA, main="school")
# seqdplot(shortenedset1del[[3]][[4]], group = clustersfac[[1]], border = NA, main="partner")
seqIplot(shortenedset1del[[3]][[4]], sortv="from.start", group = clustersfac[[1]], border = NA, main="partner")
dev.off()
pdf("plots/seqplotsset22clustersclusteredbyset1.pdf")
# seqdplot(shortenedset1del[[3]][[1]], group = clustersfac[[1]], border = NA, main="used_public")
seqIplot(shortenedset2del[[3]][[1]], sortv="from.start", group = clustersfac[[1]], border = NA, main="used_public")
# seqdplot(shortenedset1del[[3]][[2]], group = clustersfac[[1]], border = NA, main="used_public")
seqIplot(shortenedset2del[[3]][[2]], sortv="from.start", group = clustersfac[[1]], border = NA, main="used_public")
# seqdplot(shortenedset1del[[3]][[3]], group = clustersfac[[1]], border = NA, main="used_own")
seqIplot(shortenedset2del[[3]][[3]], sortv="from.start", group = clustersfac[[1]], border = NA, main="used_own")
dev.off()
pdf("plots/seqplotsset2allclusteredbyset2.pdf")
# map(clustersfac, ~seqdplot(shortenedset2del[[3]][[1]], group = ., border = NA, main="used_walkbike"))
map(clustersfac2, ~seqIplot(shortenedset2del[[3]][[1]], sortv="from.start", group = ., border = NA, main="used_walkbike"))
# map(clustersfac, ~seqdplot(shortenedset2del[[3]][[2]], group = ., border = NA, main="used_public"))
map(clustersfac2, ~seqIplot(shortenedset2del[[3]][[2]], sortv="from.start", group = ., border = NA, main="used_public"))
# map(clustersfac, ~seqdplot(shortenedset2del[[3]][[3]], group = ., border = NA, main="used_own"))
map(clustersfac2, ~seqIplot(shortenedset2del[[3]][[3]], sortv="from.start", group = ., border = NA, main="used_own"))
dev.off()
pdf("plots/seqplotsset22clusteredbyset2.pdf")
# seqdplot(shortenedset1del[[3]][[1]], group = clustersfac[[1]], border = NA, main="used_public")
seqIplot(shortenedset2del[[3]][[1]], sortv="from.start", group = clustersfac2[[1]], border = NA, main="used_public")
# seqdplot(shortenedset1del[[3]][[2]], group = clustersfac[[1]], border = NA, main="used_public")
seqIplot(shortenedset2del[[3]][[2]], sortv="from.start", group = clustersfac2[[1]], border = NA, main="used_public")
# seqdplot(shortenedset1del[[3]][[3]], group = clustersfac[[1]], border = NA, main="used_own")
seqIplot(shortenedset2del[[3]][[3]], sortv="from.start", group = clustersfac2[[1]], border = NA, main="used_own")
dev.off()

grid.arrange(seqI)


nona<-filter(reduced35, is.na(reduced35$hhsize3))

